### ISSUE TITLE
Not able to open files. Reason : "failed to load file header (version 14000005, 20.0.0.5)"

### ISSUE THREAD

**Issue by joviint** [Nexus-Mods/discord-bot#18]
I'm not able to open some of the nif files from aura kingdom games using old version and nif 2.0 dev 7, due to "failed to load file header (version 14000005, 20.0.0.5)"
Please kindly help, thank you.

[nif.zip](https://github.com/Nexus-Mods/discord-bot/files/9926779/nif.zip)

**Comment by Pickysaurus** [comment]
This has absolutely nothing to do with this Discord bot.
