### ISSUE TITLE
Feature Request:  additional search setting parameter to change default public/private behavior for the server

### ISSUE THREAD

**Issue by Babscoole** [Nexus-Mods/discord-bot#27]
/search mods results used to be public by default, now they are private by default.  I'd like to request a new setting, similar to /settings update filter to set the game to be used for searches on the server, to set public true for searches on the server by default.

**Comment by Pickysaurus** [comment]
I may just flip the default back to public as I only changed it because our design team needed to use the search and weren't confident in making it private.

**Comment by Babscoole** [comment]
Thank you sir
