### ISSUE TITLE
/settings update filter  no longer appears to function to limit searches on the discord server to a specific game

### ISSUE THREAD

**Issue by Babscoole** [Nexus-Mods/discord-bot#28]
Per title, /settings update filter set to nomanssky.  When I try a fairly generic search, based on one keyword, /search mods companion, first page of results are for fallout 4.

**Comment by Pickysaurus** [comment]
Can verify this issue, the filter-by-game option is currently halfway through a rework so that's probably why.

**Comment by Babscoole** [comment]
Thank you sir
