### ISSUE TITLE
HTML-encoded character references in mod titles

### ISSUE THREAD

**Issue by JonathanFeenstra** [Nexus-Mods/discord-bot#7]
Sometimes the API returns [HTML-encoded character references in mod titles](https://search.nexusmods.com/mods?terms=test&game_id=110) when using the `mods` command as shown in result 2 and 3 here:
![image](https://user-images.githubusercontent.com/26406078/100515693-da663c80-3175-11eb-8164-10143ff24160.png)

For my modlinkbot I use Python's [`html.unescape`](https://docs.python.org/3/library/html.html#html.unescape) method to resolve this, the closest JavaScript equivalent I could find was [`he.decode`](https://github.com/mathiasbynens/he#hedecodehtml-options).

**Comment by Pickysaurus** [comment]
This actually seems to be a problem with the data stored on Nexus Mods. Some data is encoded, other data isn't.

**Comment by Pickysaurus** [comment]
I believe this has been fixed on the API end.
